//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34014
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaiwanTrain.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaiwanTrain.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 台灣鐵路時刻表 的當地語系化字串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///	&quot;1100&quot;:&quot;自強號&quot;,
        ///	&quot;1101&quot;:&quot;自強號&quot;,
        ///	&quot;1102&quot;:&quot;自強(太魯閣號)&quot;,
        ///	&quot;1107&quot;:&quot;新自強&quot;,
        ///	&quot;1110&quot;:&quot;莒光&quot;,
        ///	&quot;1120&quot;:&quot;復興&quot;,
        ///	&quot;1130&quot;:&quot;電車&quot;,
        ///	&quot;1131&quot;:&quot;區間車&quot;,
        ///	&quot;1132&quot;:&quot;區間快&quot;,
        ///	&quot;1140&quot;:&quot;普快車&quot;,
        ///	&quot;1141&quot;:&quot;柴快車&quot;,
        ///	&quot;1150&quot;:&quot;柴油車&quot;,
        ///} 的當地語系化字串。
        /// </summary>
        public static string CarClass {
            get {
                return ResourceManager.GetString("CarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CarClass.txt 的當地語系化字串。
        /// </summary>
        public static string CarClassFile {
            get {
                return ResourceManager.GetString("CarClassFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最愛中已存在相同的路徑\n請重新選取。 的當地語系化字串。
        /// </summary>
        public static string FavoriteRouteExistedErrorMessage {
            get {
                return ResourceManager.GetString("FavoriteRouteExistedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 從 的當地語系化字串。
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 釘選至動態磚 的當地語系化字串。
        /// </summary>
        public static string PinToStartMenu {
            get {
                return ResourceManager.GetString("PinToStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我的最愛 的當地語系化字串。
        /// </summary>
        public static string PivotItem1_MyFavorite {
            get {
                return ResourceManager.GetString("PivotItem1_MyFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        public static string PivotItem2_Search {
            get {
                return ResourceManager.GetString("PivotItem2_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 推薦車次 的當地語系化字串。
        /// </summary>
        public static string PivotItem3_SuggestTrain {
            get {
                return ResourceManager.GetString("PivotItem3_SuggestTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LeftToRight 的當地語系化字串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 zh-TW 的當地語系化字串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 路線 的當地語系化字串。
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起始站與終點站不可為同一站\n請重新選取。 的當地語系化字串。
        /// </summary>
        public static string SameStationErrorMessage {
            get {
                return ResourceManager.GetString("SameStationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定 的當地語系化字串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {
        ///	&quot;1001&quot;:&quot;基隆&quot;,
        ///	&quot;1002&quot;:&quot;八堵&quot;,
        ///	&quot;1003&quot;:&quot;七堵&quot;,
        ///	&quot;1004&quot;:&quot;五堵&quot;,
        ///	&quot;1005&quot;:&quot;汐止&quot;,
        ///	&quot;1006&quot;:&quot;南港&quot;,
        ///	&quot;1007&quot;:&quot;松山&quot;,
        ///	&quot;1008&quot;:&quot;台北&quot;,
        ///	&quot;1009&quot;:&quot;萬華&quot;,
        ///	&quot;1011&quot;:&quot;板橋&quot;,
        ///	&quot;1032&quot;:&quot;浮洲&quot;,
        ///	&quot;1012&quot;:&quot;樹林&quot;,
        ///	&quot;1013&quot;:&quot;山佳&quot;,
        ///	&quot;1014&quot;:&quot;鶯歌&quot;,
        ///	&quot;1015&quot;:&quot;桃園&quot;,
        ///	&quot;1016&quot;:&quot;內壢&quot;,
        ///	&quot;1017&quot;:&quot;中壢&quot;,
        ///	&quot;1018&quot;:&quot;埔心&quot;,
        ///	&quot;1019&quot;:&quot;楊梅&quot;,
        ///	&quot;1020&quot;:&quot;富岡&quot;,
        ///	&quot;1021&quot;:&quot;湖口&quot;,
        ///	&quot;1022&quot;:&quot;新豐&quot;,
        ///	&quot;1023&quot;:&quot;竹北&quot;,
        ///	&quot;1024&quot;:&quot;北新竹&quot;,
        ///	&quot;1025&quot;:&quot;新竹&quot;,
        ///	&quot;1026&quot;:&quot;香山&quot;,
        ///	&quot;1027&quot;:&quot;崎頂&quot;,
        ///	&quot;1028&quot;:&quot;竹南&quot;,
        ///	&quot;1029&quot;:&quot;三坑&quot;,
        ///	&... 的當地語系化字串。
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station.txt 的當地語系化字串。
        /// </summary>
        public static string StationFile {
            get {
                return ResourceManager.GetString("StationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇站名 的當地語系化字串。
        /// </summary>
        public static string StationPicker {
            get {
                return ResourceManager.GetString("StationPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到 的當地語系化字串。
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 今明兩天 的當地語系化字串。
        /// </summary>
        public static string TodayAndTmrr {
            get {
                return ResourceManager.GetString("TodayAndTmrr", resourceCulture);
            }
        }
    }
}
